// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Nauck IT KG")]
[assembly: AssemblyProductAttribute("Portable.Licensing")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2012 - 2014 Nauck IT KG")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
